sudo: required

language: node_js

before_install:
  - docker build -t soichih/warehouse . 

install:
  - npm install

services: 
  - mongodb
  - docker

script:
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

after_success: 
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push soichih/warehouse

#notifications:
#  slack: research-technologies:izdZdry8NEjrDmTjbHL5dCA8
